"""Action handler modules extracted from app.py.

Submodules: library_actions, search_api_actions, external_io_actions,
llm_actions, ui_actions. Each exposes ``action_*(app)`` functions that
accept an ``ArxivBrowser`` instance and implement a single keybinding action.
"""

from __future__ import annotations

from typing import Any


def build_action_registry() -> dict[str, Any]:
    """Build a mapping of attribute names to action handler callables.

    Returns a dict suitable for ``setattr`` registration on ``ArxivBrowser``.
    """
    from arxiv_browser.actions import (
        external_io_actions,
        library_actions,
        llm_actions,
        search_api_actions,
        ui_actions,
    )

    return {
        "action_toggle_search": search_api_actions.action_toggle_search,
        "action_cancel_search": search_api_actions.action_cancel_search,
        "action_ctrl_e_dispatch": ui_actions.action_ctrl_e_dispatch,
        "action_toggle_s2": ui_actions.action_toggle_s2,
        "action_fetch_s2": ui_actions.action_fetch_s2,
        "_fetch_s2_paper_async": ui_actions._fetch_s2_paper_async,
        "action_toggle_hf": ui_actions.action_toggle_hf,
        "_fetch_hf_daily": ui_actions._fetch_hf_daily,
        "_fetch_hf_daily_async": ui_actions._fetch_hf_daily_async,
        "action_check_versions": ui_actions.action_check_versions,
        "action_exit_arxiv_search_mode": search_api_actions.action_exit_arxiv_search_mode,
        "action_arxiv_search": search_api_actions.action_arxiv_search,
        "_format_arxiv_search_label": search_api_actions._format_arxiv_search_label,
        "_apply_arxiv_rate_limit": search_api_actions._apply_arxiv_rate_limit,
        "_fetch_arxiv_api_page": search_api_actions._fetch_arxiv_api_page,
        "_apply_arxiv_search_results": search_api_actions._apply_arxiv_search_results,
        "_run_arxiv_search": search_api_actions._run_arxiv_search,
        "action_cursor_down": library_actions.action_cursor_down,
        "action_cursor_up": library_actions.action_cursor_up,
        "action_toggle_select": library_actions.action_toggle_select,
        "action_select_all": library_actions.action_select_all,
        "action_clear_selection": library_actions.action_clear_selection,
        "action_cycle_sort": library_actions.action_cycle_sort,
        "action_toggle_read": library_actions.action_toggle_read,
        "action_toggle_star": library_actions.action_toggle_star,
        "action_edit_notes": library_actions.action_edit_notes,
        "action_edit_tags": library_actions.action_edit_tags,
        "_collect_all_tags": llm_actions._collect_all_tags,
        "action_toggle_watch_filter": library_actions.action_toggle_watch_filter,
        "action_manage_watch_list": library_actions.action_manage_watch_list,
        "action_mark_visible_read": library_actions.action_mark_visible_read,
        "action_goto_bookmark": search_api_actions.action_goto_bookmark,
        "action_add_bookmark": search_api_actions.action_add_bookmark,
        "action_remove_bookmark": search_api_actions.action_remove_bookmark,
        "action_copy_bibtex": external_io_actions.action_copy_bibtex,
        "action_export_bibtex_file": external_io_actions.action_export_bibtex_file,
        "action_export_markdown": external_io_actions.action_export_markdown,
        "action_export_menu": external_io_actions.action_export_menu,
        "_do_export": external_io_actions._do_export,
        "_get_export_dir": external_io_actions._get_export_dir,
        "_export_to_file": external_io_actions._export_to_file,
        "_export_clipboard_ris": external_io_actions._export_clipboard_ris,
        "_export_clipboard_csv": external_io_actions._export_clipboard_csv,
        "_export_clipboard_mdtable": external_io_actions._export_clipboard_mdtable,
        "_export_file_ris": external_io_actions._export_file_ris,
        "_export_file_csv": external_io_actions._export_file_csv,
        "action_export_metadata": external_io_actions.action_export_metadata,
        "action_import_metadata": external_io_actions.action_import_metadata,
        "action_show_similar": ui_actions.action_show_similar,
        "_fetch_s2_recommendations_async": ui_actions._fetch_s2_recommendations_async,
        "action_citation_graph": ui_actions.action_citation_graph,
        "_fetch_citation_graph": ui_actions._fetch_citation_graph,
        "action_cycle_theme": ui_actions.action_cycle_theme,
        "action_toggle_sections": ui_actions.action_toggle_sections,
        "action_show_help": ui_actions.action_show_help,
        "action_command_palette": ui_actions.action_command_palette,
        "action_collections": ui_actions.action_collections,
        "action_add_to_collection": ui_actions.action_add_to_collection,
        "_trust_hash": staticmethod(llm_actions._trust_hash),
        "_remember_trusted_hash": llm_actions._remember_trusted_hash,
        "_is_llm_command_trusted": llm_actions._is_llm_command_trusted,
        "_is_pdf_viewer_trusted": llm_actions._is_pdf_viewer_trusted,
        "_ensure_command_trusted": llm_actions._ensure_command_trusted,
        "_ensure_llm_command_trusted": llm_actions._ensure_llm_command_trusted,
        "_ensure_pdf_viewer_trusted": llm_actions._ensure_pdf_viewer_trusted,
        "_require_llm_command": llm_actions._require_llm_command,
        "action_generate_summary": llm_actions.action_generate_summary,
        "_start_summary_flow": llm_actions._start_summary_flow,
        "_on_summary_mode_selected": llm_actions._on_summary_mode_selected,
        "_generate_summary_async": llm_actions._generate_summary_async,
        "action_chat_with_paper": llm_actions.action_chat_with_paper,
        "_start_chat_with_paper": llm_actions._start_chat_with_paper,
        "_open_chat_screen": llm_actions._open_chat_screen,
        "action_score_relevance": llm_actions.action_score_relevance,
        "_start_score_relevance_flow": llm_actions._start_score_relevance_flow,
        "_on_interests_saved_then_score": llm_actions._on_interests_saved_then_score,
        "_start_relevance_scoring": llm_actions._start_relevance_scoring,
        "action_edit_interests": llm_actions.action_edit_interests,
        "_on_interests_edited": llm_actions._on_interests_edited,
        "_score_relevance_batch_async": llm_actions._score_relevance_batch_async,
        "_update_relevance_badge": llm_actions._update_relevance_badge,
        "action_auto_tag": llm_actions.action_auto_tag,
        "_start_auto_tag_flow": llm_actions._start_auto_tag_flow,
        "_auto_tag_single_async": llm_actions._auto_tag_single_async,
        "_auto_tag_batch_async": llm_actions._auto_tag_batch_async,
        "_start_downloads": external_io_actions._start_downloads,
        "_process_single_download": external_io_actions._process_single_download,
        "_finish_download_batch": external_io_actions._finish_download_batch,
        "action_open_url": external_io_actions.action_open_url,
        "_do_open_urls": external_io_actions._do_open_urls,
        "action_open_pdf": external_io_actions.action_open_pdf,
        "_do_open_pdfs": external_io_actions._do_open_pdfs,
        "_open_with_viewer": external_io_actions._open_with_viewer,
        "action_download_pdf": external_io_actions.action_download_pdf,
        "_do_start_downloads": external_io_actions._do_start_downloads,
        "_format_paper_for_clipboard": external_io_actions._format_paper_for_clipboard,
        "_copy_to_clipboard": external_io_actions._copy_to_clipboard,
        "action_copy_selected": external_io_actions.action_copy_selected,
        "action_prev_date": search_api_actions.action_prev_date,
        "action_next_date": search_api_actions.action_next_date,
    }


__all__ = ["build_action_registry"]
