#!/usr/bin/env python3
"""Enforce measurable repository quality budgets."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

STATEMENT_COVERAGE_MIN = 96.0
BRANCH_COVERAGE_MIN = 90.0
INTERACTIVE_COVERAGE_MIN = 94.0
SOURCE_LINE_SOFT_CAP = 1000
NEAR_CAP_LINE_BUDGETS = {
    "src/arxiv_browser/browser/core.py": 938,
    "src/arxiv_browser/config.py": 921,
    "src/arxiv_browser/cli.py": 900,
}
INTERACTIVE_PREFIXES = (
    "src/arxiv_browser/actions/",
    "src/arxiv_browser/browser/",
)
INTERACTIVE_FILES = {"src/arxiv_browser/cli.py"}


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Check coverage and source-size quality budgets")
    parser.add_argument(
        "report",
        nargs="?",
        default="coverage.json",
        help="Path to coverage JSON report generated by pytest-cov",
    )
    parser.add_argument(
        "--src-root",
        default="src/arxiv_browser",
        help="Source tree to scan for Python file-size budgets",
    )
    return parser.parse_args()


def _load_coverage(report_path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(report_path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise SystemExit(f"Coverage report not found: {report_path}") from None
    except json.JSONDecodeError as exc:
        raise SystemExit(f"Invalid coverage JSON in {report_path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise SystemExit(f"Invalid coverage JSON root in {report_path}")
    return payload


def _coverage_total(payload: dict[str, Any], key: str, report_path: Path) -> float:
    totals = payload.get("totals")
    if not isinstance(totals, dict):
        raise SystemExit(f"Coverage report missing totals: {report_path}")
    value = totals.get(key)
    if value is None:
        raise SystemExit(f"Coverage report missing totals.{key}: {report_path}")
    return float(value)


def _interactive_coverage(payload: dict[str, Any], report_path: Path) -> float:
    files = payload.get("files")
    if not isinstance(files, dict):
        raise SystemExit(f"Coverage report missing files: {report_path}")

    covered = 0
    total = 0
    for file_path, data in files.items():
        if not (
            file_path in INTERACTIVE_FILES
            or any(file_path.startswith(prefix) for prefix in INTERACTIVE_PREFIXES)
        ):
            continue
        if not isinstance(data, dict):
            continue
        summary = data.get("summary")
        if not isinstance(summary, dict):
            continue
        statements = int(summary.get("num_statements", 0))
        missing_lines = int(summary.get("missing_lines", 0))
        branches = int(summary.get("num_branches", 0))
        missing_branches = int(summary.get("missing_branches", 0))
        covered += statements - missing_lines + branches - missing_branches
        total += statements + branches

    if total == 0:
        raise SystemExit(f"Coverage report has no interactive module entries: {report_path}")
    return covered * 100.0 / total


def _tracked_source_files(src_root: Path) -> list[Path]:
    return sorted(path for path in src_root.rglob("*.py") if path.is_file())


def _line_count(path: Path) -> int:
    return len(path.read_text(encoding="utf-8").splitlines())


def _check_file_size_budgets(src_root: Path) -> list[str]:
    failures: list[str] = []
    for path in _tracked_source_files(src_root):
        rel_path = path.as_posix()
        lines = _line_count(path)
        if lines > SOURCE_LINE_SOFT_CAP:
            failures.append(f"{rel_path}: {lines} lines > soft cap {SOURCE_LINE_SOFT_CAP}")
        budget = NEAR_CAP_LINE_BUDGETS.get(rel_path)
        if budget is not None and lines > budget:
            failures.append(f"{rel_path}: {lines} lines > quality budget {budget}")
    return failures


def _budget_result(name: str, value: float, minimum: float) -> tuple[bool, str]:
    ok = value >= minimum
    return ok, f"{name}: {value:.2f}% >= {minimum:.2f}%"


def main() -> int:
    args = _parse_args()
    report_path = Path(args.report)
    src_root = Path(args.src_root)
    payload = _load_coverage(report_path)

    checks = [
        _budget_result(
            "statement coverage",
            _coverage_total(payload, "percent_statements_covered", report_path),
            STATEMENT_COVERAGE_MIN,
        ),
        _budget_result(
            "branch coverage",
            _coverage_total(payload, "percent_branches_covered", report_path),
            BRANCH_COVERAGE_MIN,
        ),
        _budget_result(
            "interactive module coverage",
            _interactive_coverage(payload, report_path),
            INTERACTIVE_COVERAGE_MIN,
        ),
    ]
    failures = [message for ok, message in checks if not ok]
    failures.extend(_check_file_size_budgets(src_root))

    for _ok, message in checks:
        print(message)
    if not failures:
        print("source file-size budgets: ok")
        return 0

    print("Quality budget failure(s):", file=sys.stderr)
    for failure in failures:
        print(f"- {failure}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
